language: node_js
node_js:
  - "stable"

cache:
  directories:
    - "$HOME/.npm"

services:
  - postgresql

before_script:
  # - createdb pms_test
  - npm install
  - npm install -g sequelize-cli

script:
  - npm test

addons:
  postgresql: "9.3"
